### ISSUE TITLE
On Spigot 1.8, while porting an image to map.

### ISSUE THREAD

**Issue by MetalGearDaner** [Coutume/ImageOnMap#1]
http://i.imgur.com/DTGaPAI.png

**Comment by Coutume** [comment]
Hi,
Did you use the latest sourc code from GitHub ?

**Comment by MetalGearDaner** [comment]
Yes, I use the source of the repository compiled. Also, there is an error con where all the maps get deleted. If you would like to fixed those errors, I could give you more information as console logs, etc.

**Comment by Coutume** [comment]
Yes, why not. But I can not guarantee you to fix it quickly.

**Comment by MetalGearDaner** [comment]
Spigot 1.8.1 build:
http://i.imgur.com/L9hPP2w.png

Bugs on the plugin:
- Whenever you restart the server all the images get deleted, so that they have to be created another time.
- Colors aren't correctly rendered, images are like 8bits.
- When you create a imagetomap, the localition on the hole image of each maps aren't printed appropriately.

**Comment by MetalGearDaner** [comment]
Maps are like: http://prntscr.com/64z3ur

**Comment by prokopyl** [comment]
Minecraft maps can't render all the possible colors : they are limited to a specific palette where each color represent a specific block (therefore creating this 8bit-ish sensation). There's nothing that can be done about that (unless you mod both the client and the server).

As for the two other bugs, can you create separate issues for them (as they seem to be completely unrelated), and include the server log (when starting and when using /tomap) ?

**Comment by MetalGearDaner** [comment]
Sure.

**Comment by prokopyl** [comment]
#3 is actually the same problem as this one, so i'll close it as #3 is much cleaner.
