### ISSUE TITLE
Maps disappear when server restarts.

### ISSUE THREAD

**Issue by MetalGearDaner** [Coutume/ImageOnMap#3]
Whenever you restart the server, all the ImageOnMaps will disappear and you can only see them like this: http://prntscr.com/64z3ur

The /plugins/ImageOnMap/image folder seems to be always empty. Even when you create a new image to map.

The console prints this when it loads the plugin:

http://paste.ofcode.org/iNCBRAC5ncJDnF5qeUrnPJ

**Comment by prokopyl** [comment]
It seems that the maps aren't correctly saved when creating a new ImageOnMap. Can you send what shows the console when you use the /tomap command ?

**Comment by MetalGearDaner** [comment]
http://paste.ofcode.org/sRGyGnbr2iGZZirfWbQE8k

**Comment by prokopyl** [comment]
e19d8b5f39909c3dbad349bdd7c3aa6dd9b49706 should fix this, can you confirm ?

**Comment by elespawol** [comment]
Nup, it stills.... :s 
urgent...

**Comment by MetalGearDaner** [comment]
Hmm, @elespawol I've tested this version and everything works correctly. Do you want me to give you the jar file?

**Comment by prokopyl** [comment]
We recently set up jenkins builds here : http://jenkins.carrade.eu/job/ImageOnMap/, if you want to directly use development versions. 
You can directly get the build of the lastest revision here : http://jenkins.carrade.eu/job/ImageOnMap/lastSuccessfulBuild/artifact/target/ImageOnMap-1.0.jar (for testing purposes only !) (and yes, version number is not updated, that will be fixed soon).

@elespawol If you still have a bug with this lastest version, I will need quite a bit more information (such as system information, server logs, etc.).

**Comment by elespawol** [comment]
i builded yesterday... the plugin... with maven and jdk
I will test to rebuild and see what happens.
Thanks

**Comment by MetalGearDaner** [comment]
Maps aren't been loaded. The same bloody problem.

http://i.imgur.com/fD81hYF.png

**Comment by prokopyl** [comment]
Won't fix, as this only affects an old and buggy development version (see #8 for a proper explanation).
