### ISSUE TITLE
More errors with maps

### ISSUE THREAD

**Issue by MetalGearDaner** [Coutume/ImageOnMap#8]
Some maps are not show when server restarts. When I click with the middle button a map not loaded correctly, it gaves me the image on a map and apparently, then, the map loads correctly the image. But when the server restarts, the problem continues.

http://i.imgur.com/xSg2rJ1.png

Error on console:
http://paste.ofcode.org/uLZZpGM5ch5MCyAz7qQeqi

All images are correctly loaded on the /images folder:
http://prntscr.com/6dd5n8

**Comment by prokopyl** [comment]
Oh, I didn't see you edited your message after posting the bug report (I watch the issues mainly using my mail client, and all I saw was the message "some map not show/no errors on console"). Sorry about that.

The more I dig into the old code, the more problems show up. And with the upcoming 3.0 major version that I'm working on (in the indev branch), I'll have to admit that I'm kind of tired of patching old code that will be dropped soon anyway.

So I'm asking you : dou you have any problems (this issue + all of the others you reported previously) with the stable 2.7 release (the one you will find on bukkitdev), that force you to use this unstable development version ? 
If you do, then I will work on fixing these and releasing a 2.7.1 version that will contain all the needed bugfixes. If 2.7 works well for you, then I won't waste any time patching the old code, and focus on the new 3.0 version (that will fix anything anyway, as everything will be rewritten).

PS: Thanks for your time and reporting these issues, and sorry again for the response time.

**Comment by MetalGearDaner** [comment]
The devbukkit one didn't event loads while server starts, I recommend you to focus on the 3.0 stable version in order to release it as fasters as you can with all the old code rewritten. Right now, the plugin only spams the console with erros, but ingame, everything seems to work appropiately.

**Comment by prokopyl** [comment]
Alright, thanks. :)
From now on I will focus on the 3.0 version. I plan to gradually re-implement all the functionalities of the current 2.7 version, but with a much more robust backend. Once this this done, I will merge the two branches, and release a 3.0 alpha version for everyone to try out. 
After that, I will be able to peacefully add fancy new features and fix all the bugs we can find (not much I hope !).

As a result of this plan, I will mark the still open issues as "won't fix", as they affect a version that will probably never come out.
