### ISSUE TITLE
Re-implement the features of the 2.7 version

### ISSUE THREAD

**Issue by prokopyl** [Coutume/ImageOnMap#9]
- [x] Basic threading for heavy operations.
- [x] Map loading (from disk) and rendering.
- [x] Commands management.
- [x] New map data storing system.
- [x] Map and rendering (from URL).
- [x] Map management (CRUD).
- [x] Per-player and global server map limit.

**Comment by MetalGearDaner** [comment]
Hello, do you know aproximately when could the version 3.0 be available?

**Comment by prokopyl** [comment]
I am hoping to be able to release it in approximately a month.
However, I think I should be able to release the Alpha 1 in about a week, so you won't have to wait for all the new features to come out in order to have the optimized and (hopefully!) bug-free version. :)

**Comment by prokopyl** [comment]
All of the features of v2.7 are working correctly now !
The only thing left is the migration system for the v2.7 -> v3.0, and the Alpha 1 will be released.

**Comment by MetalGearDaner** [comment]
Great! Right now I don't have any map in my server because of the problems with version 2.7. I'd appreciate a lot if you could give me the first 3.0 plugin jar without the migration system.

Regards and good job

**Comment by AmauryCarrade** [comment]
The compiled versions are already published [on a continuous integration server, here](http://jenkins.carrade.eu/job/ImageOnMap/).
